// Structure and timing only — every viewer-facing string lives in
// src/copy/en.json (read via copy.checkpoints[cp.id], copy.intro, copy.footer).
// The prose fields below are the handoff contract for real captures; they are
// rendered into CAPTURE.md by scripts/capture-doc.ts, never on screen.

export type CheckpointId = "brief" | "shortlist" | "forensic" | "call" | "handoff" | "stack";
export type SegmentId = "intro" | CheckpointId;

export type Badge = {
  label: string;
  // File name under public/badges/ (e.g. "nebius.png"). Undefined renders a
  // text chip; fill it in once the extracted logo file exists.
  logo?: string;
  tone?: "neutral" | "accent";
};

export type ClipSource =
  | { kind: "placeholder" }
  | { kind: "clip"; file: string; trimStartSec?: number };

export type Checkpoint = {
  id: CheckpointId;
  tailFrames?: number; // breathing room after the VO ends, default 24
  badges: Badge[]; // sponsor/tech fired in this step
  mustShow: string[]; // handoff checklist for the real capture
  startState: string; // handoff prose, not on screen
  actions: string[];
  endState: string;
  transition: string;
  source: ClipSource;
  // Default true: the scene renders inside the phone frame. False renders the
  // scene across the full left zone instead (used by the stack diagram).
  showPhone?: boolean;
};

export type DemoConfig = {
  fps: 30;
  width: 1920;
  height: 1080;
  // `voice.voice` is passed to `pocket-tts --voice`: a built-in voice name
  // ("alba", "marius", ...) or a path to a .safetensors/.wav voice file
  // resolved relative to apps/video (e.g. "voices/you.safetensors"). For
  // file paths the TTS cache hashes the file contents, so re-exporting the
  // file regenerates every segment. `voice.tempo` is an ffmpeg atempo
  // factor applied to each WAV in post (pocket-tts has no rate control);
  // 0.80 to 0.90 is the clean narration range, 1.0 disables.
  voice: { engine: "pocket-tts" | "slng"; voice: string; tempo: number };
  music: { file: string | undefined; duckDb: number; swellDb: number };
  footer: { repoUrl: string | undefined; showFromSecBeforeEnd: number };
  showMockTags: boolean;
  // Sponsor strip rendered in the last checkpoint's sidebar footer. All logos
  // share one fixed height; undefined logo fields render as text chips until
  // the files land in public/badges/.
  sponsors: Badge[];
  intro: { tailFrames?: number };
  checkpoints: Checkpoint[];
};

export const demoConfig: DemoConfig = {
  fps: 30,
  width: 1920,
  height: 1080,
  // Shipped narrator: alba's precomputed voice state, committed so every
  // machine renders the same voice without depending on the HF voice
  // catalog. To narrate with a built-in instead, set voice to its name
  // ("alba"); to use your own voice, see "Use your own voice" in README.md.
  voice: {
    engine: "pocket-tts",
    voice: "voices/chezy-narrator.safetensors",
    tempo: 0.88,
  },
  // bed.wav is generated by `mise run video:music`; MusicBed mounts only when
  // a file is set. Set file back to undefined for the no-bed fallback.
  music: { file: "bed.wav", duckDb: -24, swellDb: -14 },
  footer: {
    repoUrl: "https://github.com/espetro/chezy",
    showFromSecBeforeEnd: 8,
  },
  showMockTags: true,
  sponsors: [
    { label: "Vonage", logo: "vonage.png" },
    { label: "Nebius", logo: "nebius.png" },
    { label: "Cognition", logo: "cognition.png" },
    { label: "QualityClouds", logo: "qualityclouds.png" },
    { label: "SLNG", logo: "slng.png" },
  ],
  intro: { tailFrames: 15 },
  checkpoints: [
    {
      id: "brief",
      badges: [{ label: "Nebius", logo: "nebius.png" }],
      mustShow: ["identity line", "three profile fields", "confirmation"],
      startState: 'Empty chat, greeting "What flat are you looking for?", composer focused.',
      actions: [
        'User bubble "Hi, I\'m Jessie" types in (40 ms/char).',
        "Assistant asks for neighbourhoods, monthly budget, bedrooms.",
        'User answers "Gràcia or Eixample, 1,800 a month, 2 bedrooms."',
        "Assistant confirms the saved profile and asks what else matters.",
      ],
      endState: "Four bubbles visible, profile confirmation last.",
      transition: "Chat scrolls up 300 ms ease-out, next user bubble appears.",
      source: { kind: "placeholder" },
    },
    {
      id: "shortlist",
      badges: [{ label: "Nebius", logo: "nebius.png" }],
      mustShow: ["query bubble", "3 cards", "price/m² vs average on each"],
      startState: "Previous chat scrolled so the last confirmation is at the top.",
      actions: [
        'User asks "Find me a bright 2-bed in Gràcia under €1,800."',
        'Assistant replies "Three candidates."',
        "Three ListingCard-shaped cards stagger in 80 ms apart: photo block, price, specs, zone, price/m² line with barrio average.",
      ],
      endState: "Three cards visible, card 1 top.",
      transition: "Cards 1 and 2 stay, card 3 fades; insight cards attach beneath 1 and 2.",
      source: { kind: "placeholder" },
    },
    {
      id: "forensic",
      badges: [{ label: "Nebius", logo: "nebius.png" }],
      mustShow: ["amber price flag with explicit unknowns", "green pass", "both cards"],
      startState: "Cards 1 and 2 visible.",
      actions: [
        'Assistant says "I checked both against the listing data."',
        "Amber insight card under card 1: 37,5 €/m² is the priciest per square metre of the three, floor and orientation not in the listing so they stay unknown; three bullets in Spanish italic.",
        "Green line under card 2: grounded check passed, terrace listed, 77 m², within budget.",
        "Stage push-in on the phone from scale 1.0 to 1.12 over 6 s while the amber card is read, then back.",
      ],
      endState: "Amber card and green line visible.",
      transition: "Push-out, user bubble appears.",
      source: { kind: "placeholder" },
    },
    {
      id: "call",
      badges: [
        { label: "SLNG", logo: "slng.png" },
        { label: "Vonage", logo: "vonage.png" },
      ],
      mustShow: [
        "approval bubble",
        "simulated dialing state",
        "AI disclosure line",
        "truthful outcome line",
      ],
      startState: "Forensic end state.",
      actions: [
        'User asks "Arrange a viewing for the Poblenou one." (0 to ~10 s)',
        "Assistant: \"Simulating the agency call in Spanish. I'd say I'm an AI assistant. Tick the box if you want a live demo call instead.\"",
        "Dialing card: phone icon, masked +34 number, pulsing dot, badges from config.",
        "Dialing card expands to a call sheet (~10 s to end): synthetic waveform keyed to transcript lines; four es/en transcript lines appear in sync with the VO; footer line shows the truthful outcome line.",
      ],
      endState: "Call sheet with four lines and the truthful outcome line.",
      transition: 'Call sheet collapses into a "Simulation ended" chip, chat continues.',
      source: { kind: "placeholder" },
    },
    {
      id: "handoff",
      badges: [],
      mustShow: ["truthful status bubble", "no calendar tile", "all five sidebar items checked"],
      startState: "Chat with the simulation-ended chip.",
      actions: [
        'Assistant: "Viewing call simulated for the Poblenou 2-bed. Nothing was booked."',
        "Second assistant bubble describes the live-mode dispatched state.",
      ],
      endState: "Two status bubbles.",
      transition: "Chat holds; the left zone swaps the phone frame for the stack diagram.",
      source: { kind: "placeholder" },
    },
    {
      id: "stack",
      badges: [
        { label: "Vonage", logo: "vonage.png" },
        { label: "Nebius", logo: "nebius.png" },
        { label: "Cognition", logo: "cognition.png" },
        { label: "QualityClouds", logo: "qualityclouds.png" },
        { label: "SLNG", logo: "slng.png" },
      ],
      mustShow: ["pipeline nodes", "sponsor logos on nodes", "agentic loop edges"],
      startState:
        "Left zone swaps the phone frame for a full-zone diagram canvas; the sidebar shows all six items with the last one active.",
      actions: [
        "Pipeline nodes fade in left to right (~2.5 s stagger) as the VO names them: Chat UI (Next.js), LLM (Nebius logo), Listings DB (Postgres), Voice agent (SLNG logo + unmute label), Telephony (Vonage logo), Agency phone.",
        "A branch edge drops from Voice agent to a Google Calendar node.",
        "Edges run animated dashes with a travelling pulse; a faint return edge over the top closes the agentic loop.",
        '"Built with" credit chip fades in with the Cognition and QualityClouds logos.',
        "Last 8 s: sidebar footer fades in the tagline, the sponsor strip and the repo URL.",
      ],
      endState: "Full pipeline lit, edges flowing, credit chip and sidebar footer visible.",
      transition: "End of video (no outro card).",
      showPhone: false,
      source: { kind: "placeholder" },
    },
  ],
};
