// Structure and timing only — every viewer-facing string lives in
// src/copy/en.json (read via copy.checkpoints[cp.id], copy.intro, copy.footer).
// The prose fields below are the handoff contract for real captures; they are
// rendered into CAPTURE.md by scripts/capture-doc.ts, never on screen.

export type CheckpointId = "brief" | "shortlist" | "forensic" | "call" | "booked" | "stack";
export type SegmentId = "intro" | CheckpointId;

export type Badge = {
  label: string;
  // File name under public/badges/ (e.g. "nebius.png"). Undefined renders a
  // text chip; fill it in once the extracted logo file exists.
  logo?: string;
  tone?: "neutral" | "accent";
};

export type ClipSource =
  | { kind: "placeholder" }
  | { kind: "clip"; file: string; trimStartSec?: number };

export type Checkpoint = {
  id: CheckpointId;
  tailFrames?: number; // breathing room after the VO ends, default 24
  badges: Badge[]; // sponsor/tech fired in this step
  mustShow: string[]; // handoff checklist for the real capture
  startState: string; // handoff prose, not on screen
  actions: string[];
  endState: string;
  transition: string;
  source: ClipSource;
  // Default true: the scene renders inside the phone frame. False renders the
  // scene across the full left zone instead (used by the stack diagram).
  showPhone?: boolean;
};

export type DemoConfig = {
  fps: 30;
  width: 1920;
  height: 1080;
  // `voice.voice` is passed to `pocket-tts --voice`: a built-in voice name
  // ("alba", "marius", ...) or a path to a .safetensors/.wav voice file
  // resolved relative to apps/video (e.g. "voices/you.safetensors"). For
  // file paths the TTS cache hashes the file contents, so re-exporting the
  // file regenerates every segment. `voice.tempo` is an ffmpeg atempo
  // factor applied to each WAV in post (pocket-tts has no rate control);
  // 0.80 to 0.90 is the clean narration range, 1.0 disables.
  voice: { engine: "pocket-tts" | "slng"; voice: string; tempo: number };
  music: { file: string | undefined; duckDb: number; swellDb: number };
  footer: { repoUrl: string | undefined; showFromSecBeforeEnd: number };
  showMockTags: boolean;
  // Sponsor strip rendered in the last checkpoint's sidebar footer. All logos
  // share one fixed height; undefined logo fields render as text chips until
  // the files land in public/badges/.
  sponsors: Badge[];
  intro: { tailFrames?: number };
  checkpoints: Checkpoint[];
};

export const demoConfig: DemoConfig = {
  fps: 30,
  width: 1920,
  height: 1080,
  // Shipped narrator: Anabel's cloned voice state (exported from two ~17 s
  // recordings with `pocket-tts export-voice`), committed so every machine
  // renders the same voice without needing the gated HF cloning model.
  // voices/chezy-narrator.safetensors (alba) stays as a fallback. To narrate
  // with a built-in instead, set voice to its name ("alba"); to clone your
  // own voice, see "Use your own voice" in README.md.
  voice: {
    engine: "pocket-tts",
    voice: "voices/anabel.safetensors",
    tempo: 1.08,
  },
  // bed.wav is generated by `mise run video:music`; MusicBed mounts only when
  // a file is set. Set file back to undefined for the no-bed fallback.
  music: { file: "bed.wav", duckDb: -24, swellDb: -14 },
  footer: {
    repoUrl: "https://github.com/espetro/chezy",
    showFromSecBeforeEnd: 8,
  },
  showMockTags: true,
  sponsors: [
    { label: "Vonage", logo: "vonage.png" },
    { label: "Nebius", logo: "nebius.png" },
    { label: "Cognition", logo: "cognition.png" },
    { label: "QualityClouds", logo: "qualityclouds.png" },
    { label: "SLNG", logo: "slng.png" },
  ],
  intro: { tailFrames: 15 },
  checkpoints: [
    {
      id: "brief",
      badges: [{ label: "Nebius", logo: "nebius.png" }],
      mustShow: ["onboarding steps", "answers being picked", "live match counter"],
      startState: "Landing page on a 393x852 viewport, guest session, no profile.",
      actions: [
        '"Find my home" opens /onboarding; "Let\'s go" starts the interview.',
        "Budget & space scrolls through the prefilled range, then Continue.",
        "Move-in picks the Flexible radio; must-haves toggle exterior + elevator.",
        "Routine & area fills the work address and the 25 min commute radio.",
      ],
      endState: 'Routine step with the sticky "N listings match right now" counter live.',
      transition: "Cross-dissolve into the explore feed.",
      source: { file: "brief.mp4", kind: "clip" },
    },
    {
      id: "shortlist",
      badges: [{ label: "Nebius", logo: "nebius.png" }],
      mustShow: ["candidate carousel", "a discarded candidate", "rerank with Undo"],
      startState: "/explore with the loose profile applied and a full carousel.",
      actions: [
        'Two taps on "Next match" page through the matched candidates.',
        "A candidate is discarded; the feed reranks and offers Undo.",
        'The reason chips refine the feedback ("Too expensive"), then Undo restores it.',
      ],
      endState: "Carousel back at full length after the undo.",
      transition: "Slide into the match detail.",
      source: { file: "shortlist.mp4", kind: "clip" },
    },
    {
      id: "forensic",
      badges: [{ label: "Nebius", logo: "nebius.png" }],
      mustShow: [
        '"Why this home" panel',
        "evidence field under every claim",
        "the unknown trade-off",
      ],
      startState: "/explore/<id> for a 100% match, explanation panel settled.",
      actions: [
        "The panel scrolls claim by claim: listed price, listed rooms, built m².",
        'The "What to check" card names natural light as unknown, with its missing evidence field.',
        "In-beat push-in on the phone while the trade-off is narrated.",
      ],
      endState: "Trade-off card and the neighbourhood profile visible.",
      transition: "Slide into the call gate.",
      source: { file: "forensic.mp4", kind: "clip" },
    },
    {
      id: "call",
      badges: [
        { label: "SLNG", logo: "slng.png" },
        { label: "Vonage", logo: "vonage.png" },
      ],
      mustShow: ["auto-call notice", "call stages advancing", "booked slot"],
      startState: "Call gate mounting for a >=95% match (VIEWING_MODE=mock), no stored viewing.",
      actions: [
        "The gate dials on its own and shows the Demo pill.",
        "Stages advance: calling the agency, asking about the listing, proposing a slot, confirming the visit.",
        "The gate lands on the booked slot with the calendar line.",
      ],
      endState: "Visit booked card with the agreed slot.",
      transition: "Cross-dissolve into the booked receipt.",
      source: { file: "call.mp4", kind: "clip" },
    },
    {
      id: "booked",
      badges: [],
      mustShow: ["persisted booking", "slot and duration", "added to your calendar"],
      startState: "Detail page reloaded after the call: the booking survives the reload.",
      actions: [
        "The booked card shows the confirmed day, time and listing.",
        '"30 min · added to your calendar" reads under the slot.',
        "A slow pan over the receipt and the viewing options.",
      ],
      endState: "Booked receipt visible.",
      transition: "Cross-dissolve; the left zone swaps the phone frame for the stack diagram.",
      source: { file: "booked.mp4", kind: "clip" },
    },
    {
      id: "stack",
      badges: [
        { label: "Vonage", logo: "vonage.png" },
        { label: "Nebius", logo: "nebius.png" },
        { label: "Cognition", logo: "cognition.png" },
        { label: "QualityClouds", logo: "qualityclouds.png" },
        { label: "SLNG", logo: "slng.png" },
      ],
      mustShow: ["pipeline nodes", "sponsor logos on nodes", "agentic loop edges"],
      startState:
        "Left zone swaps the phone frame for a full-zone diagram canvas; the sidebar shows all six items with the last one active.",
      actions: [
        "Pipeline nodes fade in left to right (~2.5 s stagger) as the VO names them: Chat UI (Next.js), LLM (Nebius logo), Listings DB (Postgres), Voice agent (SLNG logo + unmute label), Telephony (Vonage logo), Agency phone.",
        "A branch edge drops from Voice agent to a Google Calendar node.",
        "Edges run animated dashes with a travelling pulse; a faint return edge over the top closes the agentic loop.",
        '"Built with" credit chip fades in with the Cognition and QualityClouds logos.',
        "Last 8 s: sidebar footer fades in the tagline, the sponsor strip and the repo URL.",
      ],
      endState: "Full pipeline lit, edges flowing, credit chip and sidebar footer visible.",
      transition: "End of video (no outro card).",
      showPhone: false,
      source: { kind: "placeholder" },
    },
  ],
};
