CREATE TABLE "Listing" (
	"id" text PRIMARY KEY NOT NULL,
	"platform" text NOT NULL,
	"platformId" text NOT NULL,
	"url" text NOT NULL,
	"operation" text NOT NULL,
	"priceEur" double precision,
	"pricePeriod" text,
	"propertyType" text,
	"builtM2" double precision,
	"rooms" integer,
	"bathrooms" integer,
	"floor" text,
	"lat" double precision,
	"lon" double precision,
	"street" text,
	"neighbourhood" text,
	"district" text,
	"municipality" text,
	"postalCode" text,
	"amenities" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"publisherName" text,
	"publisherKind" text,
	"coverUrl" text,
	"media" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"publishedAt" timestamp,
	"createdAt" timestamp DEFAULT now() NOT NULL
);
