// demo.config.ts + copy -> CAPTURE.md: the per-checkpoint handoff contract for
// teammates capturing real phone footage (start state, actions, end state,
// transition, mustShow, target seconds, pixel target). Run via
// `mise run video:capture-doc`.
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { copy } from "../src/copy/copy.schema";
import { demoConfig, type SegmentId } from "../src/config/demo.config";
import { buildTimeline } from "../src/config/timeline";
import durations from "../src/generated/durations.json";

const OUT = join(import.meta.dirname, "..", "CAPTURE.md");
const timeline = buildTimeline(demoConfig, durations);

const sec = (id: SegmentId) => (durations[id] ?? 0).toFixed(1);

const lines: string[] = [
  "# CAPTURE.md — real-footage contract for the demo video",
  "",
  "> Generated by `mise run video:capture-doc` from `src/config/demo.config.ts`",
  "> and `src/copy/en.json`. Do not edit by hand; edit the config and regen.",
  "",
  "Every checkpoint is currently a Remotion-native placeholder. To swap in a",
  "real capture: record the flow below, drop the file at",
  "`apps/video/public/clips/<id>.webm` (or `.mp4`), set the checkpoint's",
  "`source` to `{ kind: \"clip\", file }` in `demo.config.ts`, then re-render.",
  "Short clips hold the last frame; long clips are trimmed to the VO",
  "(`trimStartSec` optional).",
  "",
  "**Pixel target: 393x852 CSS px portrait at deviceScaleFactor 3 =",
  "1179x2556.** Any 393:852-aspect recording works; higher is better.",
  "",
];

for (const cp of demoConfig.checkpoints) {
  const c = copy.checkpoints[cp.id];
  lines.push(`## ${c.label} (\`${cp.id}\`)`);
  lines.push("");
  lines.push(`_${c.subtext}_`);
  lines.push("");
  lines.push(`- **Target seconds:** ${sec(cp.id)} (VO) + 0.5 s tail`);
  lines.push(`- **Callout:** ${c.callout}`);
  lines.push(`- **Start state:** ${cp.startState}`);
  lines.push("- **Actions:**");
  for (const a of cp.actions) lines.push(`  - ${a}`);
  lines.push(`- **End state:** ${cp.endState}`);
  lines.push(`- **Transition:** ${cp.transition}`);
  lines.push("- **Must show:**");
  for (const m of cp.mustShow) lines.push(`  - ${m}`);
  if (cp.badges.length > 0) {
    lines.push(`- **Badges:** ${cp.badges.map((b) => b.label).join(", ")}`);
  }
  lines.push(`- **VO:** ${c.vo}`);
  lines.push("");
}

writeFileSync(OUT, `${lines.join("\n")}\n`);
console.log(`wrote ${OUT}`);
